# NOTE: uncomment the whole file if you want to use semantic release
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "Release to GitHub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
